config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  resources :students
  resources :courses
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :student

  validates_presence_of :street_address
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :enrollments
  has_many :students, through: :enrollments

  validates_presence_of :name
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :addresses
  has_many :enrollments
  has_many :courses, through: :enrollments

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/index.html.erb
<h1>All Courses</h1>

<ul>
  <% @courses.each do |course| %>
    <li>
      <%= link_to course.name, course_path(course) %><%#= course.name %>
    </li>
  <% end %>
</ul>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>

<h3>Enrolled Students:</h3>
<ul>
  <% @course.students.each do |student| %>
    <li>
      <%= student.name %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBasicsChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/index.html.erb
<h1>All Students</h1>

<ul>
  <% @students.each do |student| %>
    <li>
      <%= link_to student.name, student_path(student) %>
    </li>
  <% end %>
</ul>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

<h3>Addresses:</h3>
<ul>
  <% @student.addresses.each do |address| %>
    <li><%= address.street_address %></li>
  <% end %>
</ul>

<h3>Courses:</h3>
<ul>
  <% @student.courses.each do |course| %>
    <li>
      <%= course.name %>
    </li>
  <% end %>
</ul>